# TCL File Generated by Component Editor 22.1
# Thu May 21 16:55:24 CEST 2026
# DO NOT MODIFY


# 
# hex_display_controller "Hex Display Controller" v1.0
# Tiziano Ceccarini 2026.05.21.16:55:24
# Displays a 20-bit integer (0 to 999999) on the six 7-segment active-low displays of the DE1-SoC (HEX0 to HEX5). Leading zeros are suppressed. Values above 999 999 show dashes. Bit 31 of the control register enables or blanks the display. BCD conversion uses a combinatorial Double Dabble circuit (no DSP blocks).
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module hex_display_controller
# 
set_module_property DESCRIPTION "Displays a 20-bit integer (0 to 999999) on the six 7-segment active-low displays of the DE1-SoC (HEX0 to HEX5). Leading zeros are suppressed. Values above 999 999 show dashes. Bit 31 of the control register enables or blanks the display. BCD conversion uses a combinatorial Double Dabble circuit (no DSP blocks)."
set_module_property NAME hex_display_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP My
set_module_property AUTHOR "Tiziano Ceccarini"
set_module_property DISPLAY_NAME "Hex Display Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL hex_display_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file hex_display_controller.vhd VHDL PATH hex_display_controller.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point mm
# 
add_interface mm avalon end
set_interface_property mm addressUnits WORDS
set_interface_property mm associatedClock clock
set_interface_property mm associatedReset reset
set_interface_property mm bitsPerSymbol 8
set_interface_property mm burstOnBurstBoundariesOnly false
set_interface_property mm burstcountUnits WORDS
set_interface_property mm explicitAddressSpan 4
set_interface_property mm holdTime 0
set_interface_property mm linewrapBursts false
set_interface_property mm maximumPendingReadTransactions 0
set_interface_property mm maximumPendingWriteTransactions 0
set_interface_property mm readLatency 0
set_interface_property mm readWaitTime 1
set_interface_property mm setupTime 0
set_interface_property mm timingUnits Cycles
set_interface_property mm writeWaitTime 0
set_interface_property mm ENABLED true
set_interface_property mm EXPORT_OF ""
set_interface_property mm PORT_NAME_MAP ""
set_interface_property mm CMSIS_SVD_VARIABLES ""
set_interface_property mm SVD_ADDRESS_GROUP ""

add_interface_port mm mm_writedata writedata Input 32
add_interface_port mm mm_readdata readdata Output 32
add_interface_port mm mm_write write Input 1
add_interface_port mm mm_read read Input 1
set_interface_assignment mm embeddedsw.configuration.isFlash 0
set_interface_assignment mm embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment mm embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment mm embeddedsw.configuration.isPrintableDevice 0


# 
# connection point hex_n
# 
add_interface hex_n conduit end
set_interface_property hex_n associatedClock clock
set_interface_property hex_n associatedReset reset
set_interface_property hex_n ENABLED true
set_interface_property hex_n EXPORT_OF ""
set_interface_property hex_n PORT_NAME_MAP ""
set_interface_property hex_n CMSIS_SVD_VARIABLES ""
set_interface_property hex_n SVD_ADDRESS_GROUP ""

add_interface_port hex_n hex0_n hex0_n Output 7
add_interface_port hex_n hex1_n hex1_n Output 7
add_interface_port hex_n hex2_n hex2_n Output 7
add_interface_port hex_n hex3_n hex3_n Output 7
add_interface_port hex_n hex4_n hex4_n Output 7
add_interface_port hex_n hex5_n hex5_n Output 7

