# TCL File Generated by Component Editor 22.1
# Thu May 21 12:03:30 CEST 2026
# DO NOT MODIFY


# 
# ov7670_data_interface "OV7670 Data Interface" v1.1
# Tiziano Ceccarini 2026.05.21.12:03:30
# Receives raw pixel data from an OV7670 camera (pclk, href, vsync, 8-bit data bus) and forwards it as an Avalon-ST source with SOP/EOP framing and backpressure support. Dropped frames are counted and exposed via an Avalon-MM slave register. Frame acquisition is controlled by software through a ctrl register (enable, camera power-down, counter clear).
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ov7670_data_interface
# 
set_module_property DESCRIPTION "Receives raw pixel data from an OV7670 camera (pclk, href, vsync, 8-bit data bus) and forwards it as an Avalon-ST source with SOP/EOP framing and backpressure support. Dropped frames are counted and exposed via an Avalon-MM slave register. Frame acquisition is controlled by software through a ctrl register (enable, camera power-down, counter clear)."
set_module_property NAME ov7670_data_interface
set_module_property VERSION 1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP My
set_module_property AUTHOR "Tiziano Ceccarini"
set_module_property DISPLAY_NAME "OV7670 Data Interface"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ov7670_data_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ov7670_data_interface.vhd VHDL PATH ov7670_data_interface.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter FRAME_SIZE INTEGER 307200 ""
set_parameter_property FRAME_SIZE DEFAULT_VALUE 307200
set_parameter_property FRAME_SIZE DISPLAY_NAME "Frame size (bytes)"
set_parameter_property FRAME_SIZE TYPE INTEGER
set_parameter_property FRAME_SIZE UNITS None
set_parameter_property FRAME_SIZE ALLOWED_RANGES 1:2147483647
set_parameter_property FRAME_SIZE DESCRIPTION "Bytes per frame: width*height for RAW8, width*height*2 for RGB565"
set_parameter_property FRAME_SIZE HDL_PARAMETER true


#
# display items
#
add_display_item "" FRAME_SIZE parameter
add_display_item "" FRAME_SIZE_NOTE text "Number of bytes per frame transferred on the Avalon-ST bus.\n  RAW8 / Grayscale : width x height         (e.g. 640x480 = 307200)\n  RGB565 / YUV422  : width x height x 2     (e.g. 640x480 = 614400)"


# 
# connection point mm
# 
add_interface mm avalon end
set_interface_property mm addressUnits WORDS
set_interface_property mm associatedClock pclk
set_interface_property mm associatedReset reset_n
set_interface_property mm bitsPerSymbol 8
set_interface_property mm burstOnBurstBoundariesOnly false
set_interface_property mm burstcountUnits WORDS
set_interface_property mm explicitAddressSpan 8
set_interface_property mm holdTime 0
set_interface_property mm linewrapBursts false
set_interface_property mm maximumPendingReadTransactions 0
set_interface_property mm maximumPendingWriteTransactions 0
set_interface_property mm readLatency 1
set_interface_property mm readWaitTime 1
set_interface_property mm setupTime 0
set_interface_property mm timingUnits Cycles
set_interface_property mm writeWaitTime 0
set_interface_property mm ENABLED true
set_interface_property mm EXPORT_OF ""
set_interface_property mm PORT_NAME_MAP ""
set_interface_property mm CMSIS_SVD_VARIABLES ""
set_interface_property mm SVD_ADDRESS_GROUP ""

add_interface_port mm mm_address address Input 1
add_interface_port mm mm_write write Input 1
add_interface_port mm mm_read read Input 1
add_interface_port mm mm_data_in writedata Input 32
add_interface_port mm mm_data_out readdata Output 32
set_interface_assignment mm embeddedsw.configuration.isFlash 0
set_interface_assignment mm embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment mm embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment mm embeddedsw.configuration.isPrintableDevice 0


# 
# connection point st_source
# 
add_interface st_source avalon_streaming start
set_interface_property st_source associatedClock pclk
set_interface_property st_source associatedReset reset_n
set_interface_property st_source dataBitsPerSymbol 8
set_interface_property st_source errorDescriptor ""
set_interface_property st_source firstSymbolInHighOrderBits true
set_interface_property st_source maxChannel 0
set_interface_property st_source readyLatency 0
set_interface_property st_source ENABLED true
set_interface_property st_source EXPORT_OF ""
set_interface_property st_source PORT_NAME_MAP ""
set_interface_property st_source CMSIS_SVD_VARIABLES ""
set_interface_property st_source SVD_ADDRESS_GROUP ""

add_interface_port st_source st_data data Output 8
add_interface_port st_source st_valid valid Output 1
add_interface_port st_source st_sop startofpacket Output 1
add_interface_port st_source st_eop endofpacket Output 1
add_interface_port st_source st_ready ready Input 1


# 
# connection point pclk
# 
add_interface pclk clock end
set_interface_property pclk clockRate 24000000
set_interface_property pclk ENABLED true
set_interface_property pclk EXPORT_OF ""
set_interface_property pclk PORT_NAME_MAP ""
set_interface_property pclk CMSIS_SVD_VARIABLES ""
set_interface_property pclk SVD_ADDRESS_GROUP ""

add_interface_port pclk pclk clk Input 1


# 
# connection point reset_n
# 
add_interface reset_n reset end
set_interface_property reset_n associatedClock pclk
set_interface_property reset_n synchronousEdges DEASSERT
set_interface_property reset_n ENABLED true
set_interface_property reset_n EXPORT_OF ""
set_interface_property reset_n PORT_NAME_MAP ""
set_interface_property reset_n CMSIS_SVD_VARIABLES ""
set_interface_property reset_n SVD_ADDRESS_GROUP ""

add_interface_port reset_n reset_n reset_n Input 1


# 
# connection point camera_if_conduit
# 
add_interface camera_if_conduit conduit end
set_interface_property camera_if_conduit associatedClock pclk
set_interface_property camera_if_conduit associatedReset reset_n
set_interface_property camera_if_conduit ENABLED true
set_interface_property camera_if_conduit EXPORT_OF ""
set_interface_property camera_if_conduit PORT_NAME_MAP ""
set_interface_property camera_if_conduit CMSIS_SVD_VARIABLES ""
set_interface_property camera_if_conduit SVD_ADDRESS_GROUP ""

add_interface_port camera_if_conduit cam_pwdn cam_pwdn Output 1
add_interface_port camera_if_conduit cam_href cam_href Input 1
add_interface_port camera_if_conduit cam_vsync cam_vsync Input 1
add_interface_port camera_if_conduit cam_data cam_data Input 8

