# TCL File Generated by Component Editor 22.1
# Thu May 21 11:45:23 CEST 2026
# DO NOT MODIFY


# 
# pclk_reset_controller "PCLK Reset Controller" v1.2
# Tiziano Ceccarini 2026.05.21.11:45:23
# Accepts the OV7670 pixel clock (pclk_in) and forwards it as a Qsys clock source (pclk_out). Controls the pclk domain reset by combining the system reset with a software-controlled release bit (Avalon-MM, bit 0). The pclk domain stays in reset until both the system reset is deasserted and software explicitly releases it, allowing the HPS to hold the pclk domain in reset during I2C camera configuration.
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module pclk_reset_controller
# 
set_module_property DESCRIPTION "Accepts the OV7670 pixel clock (pclk_in) and forwards it as a Qsys clock source (pclk_out). Controls the pclk domain reset by combining the system reset with a software-controlled release bit (Avalon-MM, bit 0). The pclk domain stays in reset until both the system reset is deasserted and software explicitly releases it, allowing the HPS to hold the pclk domain in reset during I2C camera configuration."
set_module_property NAME pclk_reset_controller
set_module_property VERSION 1.2
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP My
set_module_property AUTHOR "Tiziano Ceccarini"
set_module_property DISPLAY_NAME "PCLK Reset Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pclk_reset_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pclk_reset_controller.vhd VHDL PATH pclk_reset_controller.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point sys_reset_n
# 
add_interface sys_reset_n reset end
set_interface_property sys_reset_n associatedClock sys_clock
set_interface_property sys_reset_n synchronousEdges DEASSERT
set_interface_property sys_reset_n ENABLED true
set_interface_property sys_reset_n EXPORT_OF ""
set_interface_property sys_reset_n PORT_NAME_MAP ""
set_interface_property sys_reset_n CMSIS_SVD_VARIABLES ""
set_interface_property sys_reset_n SVD_ADDRESS_GROUP ""

add_interface_port sys_reset_n sys_reset_n reset_n Input 1


# 
# connection point sys_clock
# 
add_interface sys_clock clock end
set_interface_property sys_clock clockRate 0
set_interface_property sys_clock ENABLED true
set_interface_property sys_clock EXPORT_OF ""
set_interface_property sys_clock PORT_NAME_MAP ""
set_interface_property sys_clock CMSIS_SVD_VARIABLES ""
set_interface_property sys_clock SVD_ADDRESS_GROUP ""

add_interface_port sys_clock sys_clk clk Input 1


# 
# connection point sys_mm
# 
add_interface sys_mm avalon end
set_interface_property sys_mm addressUnits WORDS
set_interface_property sys_mm associatedClock sys_clock
set_interface_property sys_mm associatedReset sys_reset_n
set_interface_property sys_mm bitsPerSymbol 8
set_interface_property sys_mm burstOnBurstBoundariesOnly false
set_interface_property sys_mm burstcountUnits WORDS
set_interface_property sys_mm explicitAddressSpan 0
set_interface_property sys_mm holdTime 0
set_interface_property sys_mm linewrapBursts false
set_interface_property sys_mm maximumPendingReadTransactions 0
set_interface_property sys_mm maximumPendingWriteTransactions 0
set_interface_property sys_mm readLatency 1
set_interface_property sys_mm readWaitTime 1
set_interface_property sys_mm setupTime 0
set_interface_property sys_mm timingUnits Cycles
set_interface_property sys_mm writeWaitTime 0
set_interface_property sys_mm ENABLED true
set_interface_property sys_mm EXPORT_OF ""
set_interface_property sys_mm PORT_NAME_MAP ""
set_interface_property sys_mm CMSIS_SVD_VARIABLES ""
set_interface_property sys_mm SVD_ADDRESS_GROUP ""

add_interface_port sys_mm mm_writedata writedata Input  32
add_interface_port sys_mm mm_write     write     Input   1
add_interface_port sys_mm mm_readdata  readdata  Output 32
add_interface_port sys_mm mm_read      read      Input   1
set_interface_assignment sys_mm embeddedsw.configuration.isFlash 0
set_interface_assignment sys_mm embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment sys_mm embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment sys_mm embeddedsw.configuration.isPrintableDevice 0


# 
# connection point pclk_in
# 
add_interface pclk_in clock end
set_interface_property pclk_in clockRate 24000000
set_interface_property pclk_in ENABLED true
set_interface_property pclk_in EXPORT_OF ""
set_interface_property pclk_in PORT_NAME_MAP ""
set_interface_property pclk_in CMSIS_SVD_VARIABLES ""
set_interface_property pclk_in SVD_ADDRESS_GROUP ""

add_interface_port pclk_in pclk_in clk Input 1


# 
# connection point pclk_out
# 
add_interface pclk_out clock start
set_interface_property pclk_out associatedDirectClock pclk_in
set_interface_property pclk_out clockRate 24000000
set_interface_property pclk_out clockRateKnown true
set_interface_property pclk_out ENABLED true
set_interface_property pclk_out EXPORT_OF ""
set_interface_property pclk_out PORT_NAME_MAP ""
set_interface_property pclk_out CMSIS_SVD_VARIABLES ""
set_interface_property pclk_out SVD_ADDRESS_GROUP ""

add_interface_port pclk_out pclk_out clk Output 1


# 
# connection point pclk_reset_n
# 
add_interface pclk_reset_n reset start
set_interface_property pclk_reset_n associatedClock pclk_in
set_interface_property pclk_reset_n associatedResetSinks "sys_reset_n"
set_interface_property pclk_reset_n synchronousEdges DEASSERT
set_interface_property pclk_reset_n ENABLED true
set_interface_property pclk_reset_n EXPORT_OF ""
set_interface_property pclk_reset_n PORT_NAME_MAP ""
set_interface_property pclk_reset_n CMSIS_SVD_VARIABLES ""
set_interface_property pclk_reset_n SVD_ADDRESS_GROUP ""

add_interface_port pclk_reset_n pclk_reset_n reset_n Output 1

