# TCL File Generated by Component Editor 22.1
# Fri May 08 09:53:47 CEST 2026
# DO NOT MODIFY


# 
# counter_source "counter_source" v1.0
#  2026.05.08.09:53:47
# Debug Component
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module counter_source
# 
set_module_property DESCRIPTION "Debug Component"
set_module_property NAME counter_source
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME counter_source
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL counter_source
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file counter_source.vhd VHDL PATH ../my_vhdl/qsys_components/counter_source.vhd TOP_LEVEL_FILE


#
# parameters
#
add_parameter FRAME_BEATS INTEGER 38400
set_parameter_property FRAME_BEATS DISPLAY_NAME "Beats per frame"
set_parameter_property FRAME_BEATS HDL_PARAMETER true

add_parameter INITIAL_VALUE INTEGER 0
set_parameter_property INITIAL_VALUE DISPLAY_NAME "Counter initial value"
set_parameter_property INITIAL_VALUE HDL_PARAMETER true

add_parameter INCREMENT INTEGER 1
set_parameter_property INCREMENT DISPLAY_NAME "Counter increment per beat"
set_parameter_property INCREMENT HDL_PARAMETER true


#
# interfaces
#
add_interface clk clock end
add_interface_port clk clk clk Input 1

add_interface reset_n reset end
set_interface_property reset_n associatedClock clk
set_interface_property reset_n synchronousEdges DEASSERT
add_interface_port reset_n reset_n reset_n Input 1

add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clk
set_interface_property avalon_streaming_source associatedReset reset_n
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source symbolsPerBeat 8
set_interface_property avalon_streaming_source maxChannel 0
add_interface_port avalon_streaming_source avalon_streaming_source_data          data          Output 64
add_interface_port avalon_streaming_source avalon_streaming_source_valid         valid         Output 1
add_interface_port avalon_streaming_source avalon_streaming_source_ready         ready         Input  1
add_interface_port avalon_streaming_source avalon_streaming_source_startofpacket startofpacket Output 1
add_interface_port avalon_streaming_source avalon_streaming_source_endofpacket   endofpacket   Output 1


#
# display items
#

